### ISSUE TITLE
Encounter an error while saving trained model

### ISSUE THREAD

**Issue by ralgond** [hidasib/GRU4Rec_Tensorflow_Official#1]
## Environment
python==3.8.16
numpy==1.20.0
pandas==1.3.5
tensorflow==2.11
joblib==1.3.2

## The error
Saving trained model to: ./model/save_model.pt
Traceback (most recent call last):
  File "run.py", line 124, in <module>
    gru.savemodel(args.save_model)
  File "/data/thuang2/gru4rec-newsrec/GRU4Rec_Tensorflow_Official/gru4rec_tf.py", line 527, in savemodel
    joblib.dump(self, path)
  File "/data/thuang2/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 553, in dump
    NumpyPickler(f, protocol=protocol).dump(value)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 487, in dump
    self.save(obj)
  File "/data/thuang2/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 355, in save
    return Pickler.save(self, obj)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/data/thuang2/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 355, in save
    return Pickler.save(self, obj)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/data/thuang2/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 355, in save
    return Pickler.save(self, obj)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/data/thuang2/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 355, in save
    return Pickler.save(self, obj)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/data/thuang2/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 355, in save
    return Pickler.save(self, obj)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/data/thuang2/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 355, in save
    return Pickler.save(self, obj)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/data/thuang2/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 355, in save
    return Pickler.save(self, obj)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 717, in save_reduce
    save(state)
  File "/data/thuang2/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 355, in save
    return Pickler.save(self, obj)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 997, in _batch_setitems
    save(v)
  File "/data/thuang2/.local/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 355, in save
    return Pickler.save(self, obj)
  File "/data/thuang2/miniconda3/lib/python3.8/pickle.py", line 578, in save
    rv = reduce(self.proto)
TypeError: cannot pickle 'weakref' object

**Comment by hidasib** [comment]
Thanks for letting me know! I fixed it. Please update, check & let me know if it works for you!

Details:
Tensorflow is very clunky when dealing with custom stuff. This is why the `savemodel` function was already a workaround (pushing weights into numpy arrays and creating new variables when loading). 

The weird thing that it was working for me back in August when I published this code, but now I can also reproduce the error. Probably some update broke it...

Further investigation revealed that the optimizer can't be serialized now. I added a workaround that allows serializing the optimizer (get_config + numpy trick).

**Comment by ralgond** [comment]
I have test model saving and model loading, everything is ok now. Thanks for your quick response.
